import { a } from './_helpers';

const LFM = 'http://141282-the-evolution-of-la-familia-michoacan-a-case-study.pdf';
const JSTOR2 = 'https://www.jstor.org/stable/26586860?seq=1';
const GLOBAL = 'https://globalinitiative.net/wp-content/uploads/2023/03/Romain-Le-Cour-Grandmaison-Ten-years-of-vigilantes-The-Mexican-autodefensas-GI-TOC-March-2023.pdf';
const FLEEING = 'http://report-fleeing-terror-in-guerrero.pdf';

export const westCriminalFragmentation = {
  id: 'article-2',
  title: 'Criminal Fragmentation, Territorial Control, and Migration in Michoacán and Guerrero',
  author: 'Sydney Sharpley',
  excerpt: 'How criminal organizations in Michoacán and Guerrero have evolved into territorial governments — and how extortion, forced recruitment, and displacement are driving migration to the United States.',
  sections: [
    {
      heading: 'Introduction',
      paragraphs: [
        'The Mexican states of Michoacán and Guerrero have become emblematic of the profound crisis generated by organized crime. Over the past two decades, criminal groups have evolved from drug-trafficking organizations into territorial powers that govern through extortion, forced recruitment, disappearances, and social control. These dynamics have reshaped rural and urban life, targeting farmers, youth, merchants, and entire communities. As violence intensifies, patterns of internal displacement and international migration—particularly toward the United States—have accelerated. This report analyzes how criminal organizations in Michoacán and Guerrero influence migration decisions through extortion, forced recruitment, and territorial control, drawing on historical context, major actors, governance mechanisms, and the lived experiences of affected populations.',
      ],
    },
    {
      heading: 'Historical Background: The Evolution of Organized Crime',
      paragraphs: [
        'Organized crime in Michoacán and Guerrero emerged from a combination of geographic isolation, weak state presence, and the profitability of illicit markets. In the 1970s and 1980s, both states became major producers of marijuana and opium poppy, integrating local actors into transnational trafficking networks. By the 1990s, criminal groups had consolidated territorial control, exploiting longstanding grievances and the absence of effective governance.',
        `The 2000s marked a turning point with the rise of La Familia Michoacana (LFM), which blended pseudo-religious ideology with brutal ${a('enforcement', LFM)}. LFM portrayed itself as a protector of local communities, but quickly expanded into extortion, kidnapping, and forced recruitment. In Guerrero, fragmentation of larger cartels produced a proliferation of splinter groups, each seeking control over heroin production, illegal mining, and extortion ${a('economies', JSTOR2)}.`,
        `The federal government's 2006 militarized "war on drugs" destabilized existing criminal hierarchies. Military interventions fragmented cartels, creating power vacuums filled by new groups such as La Nueva Familia Michoacana (LNFM), Los Viagras, Cárteles Unidos, and the expansionist ${a('CJNG', GLOBAL)}. Instead of reducing violence, militarization dispersed it, increasing civilian exposure to conflict and weakening trust in state institutions. Communities responded by forming autodefensas (self-defense groups), especially in Michoacán's Tierra Caliente and Guerrero's Indigenous regions. While initially protective, many autodefensas were later co-opted by criminal interests or repressed by the state.`,
      ],
    },
    {
      heading: 'Major Criminal Actors',
      paragraphs: [
        `The southern regions of Michoacán and Guerrero are home to many cartels and criminal organizations that use violence and coercion against local populations. In Michoacán, La Familia Michoacana / La Nueva Familia Michoacana (LNFM)—led by the Hurtado Olascoaga brothers—now dominates parts of Tierra Caliente, controlling extortion, drug trafficking, and the avocado ${a('industry', JSTOR2)}. The Knights Templar, a splinter of LFM, established a quasi-governmental system, collecting "taxes," regulating markets, and infiltrating local politics. Los Viagras and Cárteles Unidos, initially self-defense actors, became a criminal coalition resisting CJNG's incursion. CJNG is known for militarized tactics and rapid expansion, using drones, armored vehicles, and forced recruitment.`,
        `In Guerrero, LNFM is also active, especially in mountainous poppy-producing regions. Los Ardillos, Los Tlacos, and Los Granados are highly localized groups with deep political ties, controlling extortion, mining, and drug ${a('routes', FLEEING)}. CJNG's attempts to expand into Guerrero have triggered violent clashes, including drone attacks and mass kidnappings.`,
        `Criminal groups in both states operate as parallel governments, exerting authority through violence, taxation, and regulation of daily ${a('life', JSTOR2)}. Their governance mechanisms include systematic extortion (cobro de piso) of farmers, merchants, transporters, and households; forced recruitment of youth under threat of death; kidnapping and disappearances to enforce compliance and generate revenue; market regulation dictating prices and supply chains; and political infiltration of elections and municipal governments. This "criminal governance" creates a climate in which civilians must navigate overlapping systems of coercion and survival.`,
      ],
    },
    {
      heading: 'Extortion Targeting Farmers and Agribusiness',
      paragraphs: [
        `Michoacán's avocado and lemon industries—worth billions annually—have become prime targets for extortion. Cartels charge fees per hectare, per tree, or per kilo harvested. In 2025, lemon extortion fees reached four pesos per kilo, generating over 4 billion pesos for criminal ${a('groups', JSTOR2)}. Farmers who resist face arson, kidnapping, or assassination. The murder of citrus leader Bernardo Bravo after protesting extortion exemplifies the lethal consequences of defiance. Cartels also seize land, establish their own orchards, and manipulate transportation routes, forcing many farmers into bankruptcy or displacement.`,
        `In Guerrero, extortion extends to mining, poppy cultivation, and basic goods distribution. Criminal groups tax merchants, transporters, and even schoolteachers. The 2024 killing of 11 merchants in Chautipan illustrates the extreme risks faced by those who refuse to ${a('pay', FLEEING)}.`,
      ],
    },
    {
      heading: 'Forced Recruitment and Youth Coercion',
      paragraphs: [
        `Criminal groups recruit youth through threats, abduction, or ${a('manipulation', GLOBAL)}. Boys are forced into armed roles, surveillance, or drug transport; girls face risks of trafficking and sexual violence. Families often migrate preemptively to protect children, making forced recruitment a major driver of displacement.`,
      ],
    },
    {
      heading: 'Kidnapping, Disappearances, and Coercive Control',
      paragraphs: [
        `Cartels use kidnapping and disappearance as tools of ransom extraction, punishment for resistance, terror and social control, and silencing of activists or journalists. Michoacán and Guerrero rank among Mexico's highest in disappearances, with impunity approaching 100% in some ${a('regions', JSTOR2)}. Women and girls are disproportionately targeted for trafficking or retaliation.`,
      ],
    },
    {
      heading: 'Violence, Insecurity, and Erosion of State Authority',
      paragraphs: [
        'The militarization of security has not restored order. Criminal groups challenge or replace state institutions; autodefensas emerge, fragment, or become criminalized; advanced weaponry including IEDs and drones escalates conflict; and civilians navigate shifting territorial boundaries. The result is a hybrid security landscape where state and criminal authority overlap.',
      ],
    },
    {
      heading: 'Community Responses: Self-Defense Groups',
      paragraphs: [
        'Autodefensas emerged as community responses to state failure. In Ostula, Michoacán, the Nahua Communal Guard defends against CJNG incursions despite repeated attacks. In Tierra Caliente, groups that expelled the Knights Templar later fractured or were co-opted. In Costa Chica, Guerrero, Indigenous communal police provide security but face retaliation from both criminals and the state. While initially protective, many groups now struggle with legitimacy, infiltration, or repression.',
      ],
    },
    {
      heading: 'Internal Displacement and International Migration',
      paragraphs: [
        `Displacement in both states is widespread and often sudden. The IDMC reports thousands displaced annually, with entire villages fleeing massacres, extortion demands, or recruitment ${a('threats', FLEEING)}. Indigenous communities are especially vulnerable due to territorial encroachment and limited state protection. Displaced families move to nearby urban centers, other states, or—when networks or resources allow—the United States. However, most remain unregistered and lack access to services.`,
        'Violence-driven migration from Michoacán and Guerrero has surged in recent years. Many migrants now cite extortion, recruitment, or threats as primary reasons for fleeing. Smuggling networks—often controlled by the same cartels causing displacement—charge migrants for safe passage. Failure to pay can result in kidnapping or death. The U.S.–Mexico border has become the world\'s deadliest migration route, with hundreds of deaths annually.',
        'Migration from this region increasingly comes from duress: extortion destroys livelihoods, recruitment threats endanger youth, territorial control restricts movement and access to markets, disappearances create pervasive fear, and gender-based violence forces women and girls to flee. Migration becomes a survival strategy, not a choice.',
      ],
    },
  ],
};
